// Exhibitor Terms & Conditions for the Become an Exhibitor application. The
// deposit language has been updated to match the platform's deposit policy:
// 50% of the booth (incl. additional tables) + 60% of add-ons due to reserve,
// balance due 30 days before set-up.

export const EXHIBITOR_TERMS_TITLE = 'Exhibitor Terms and Conditions';

export const EXHIBITOR_TERMS = [
  'This agreement is for Exhibit space at the 2026 For The Fans Fest.',
  'The producer of the event, Undeniable Ventures, along with the Harrah’s Resort Atlantic City and all their employees, agents, staff and production partners (herein referred to jointly as "For The Fans Fest") want to have a safe, comfortable and well-rounded event with exhibitors in numerous categories exhibiting and selling quality products that our attendees are seeking, and as an Exhibitor or Vendor at this event the applicant agrees to all terms, conditions and disclaimers in this document.',
  'This agreement, once approved, is for exhibitor space at the "For The Fans Fest" at the Harrah’s Resort Atlantic City.',
  'Exhibitor expressly understands that nothing herein shall confer any rights upon exhibitor other than those outlined herein. Exhibitor acknowledges and understands that applying for exhibit space does not guarantee an exhibit space, and that exhibiting at this event does not guarantee Exhibitor any rights to exhibit in any future shows produced by UNDENIABLE VENTURES.',
  'It is further understood that UNDENIABLE VENTURES shall have the right to reject any application and/or deny entry to any exhibitor at any time prior to or during the dates of the show, and upon return of any required refundable payments made by Exhibitors, UNDENIABLE VENTURES representing the "For The Fans Fest" shall not have any further rights, obligations or liability to the Exhibitor.',
  'Placing an order and accepting these terms does not guarantee Exhibitor a space at this event. Upon acceptance of the application by management, "For The Fans Fest" will furnish applicant with confirmation of space with payment information. Once payment is complete, load in and load out procedures, dates and times, set up, show times and security will be detailed for Exhibitor.',
  'Security will be tight for this event to ensure safety.',
  'Exhibitor promises not to attend if sick. Any government limitations due to public health issues must be followed.',
  'There are rules about the type of products that can be sold on the premises that will be detailed and enforced on property, and that if breached will cause immediate expulsion without the chance of any refund or recourse. Nothing illegal in the state of New Jersey will be allowed to be sold at the event.',
  'Sales tax is the responsibility of Exhibitors to collect according to state laws. It is your responsibility to comply with all state laws. Although this has never happened, be aware that People of Authority could be checking to see if anyone is selling any taxable product without applying NJ state Tax.',

  // ── Deposit / payment (updated to match platform policy) ───────────────────
  'PAYMENTS & DEPOSITS: All payments are to be made to Undeniable Ventures and the total amount payable under this agreement will be detailed in Exhibitor’s approval of application. To reserve your space, a deposit of 50% of the booth fee (including any additional tables) plus 60% of any add-ons (hotel nights and banquet) is due upon checkout. The remaining balance is due no later than thirty (30) days prior to show set-up day. Booth deposits are nonrefundable.',
  'If you pay by check or money order, make payment to Undeniable Ventures and send payment to 6 Pilgrim Drive, Succasunna NJ 07876. If you pay by credit card it will be charged at that time. You can save fees by paying by check or money order.',
  'No Exhibitors will be permitted to enter the property unless the balance due for the space is paid in full. Failure to pay in full could result in the loss of your deposit and booth.',
  'Cancellations must be made in writing at least 14 (fourteen) days in advance of the event. There are no refunds, although space may be able to be transferred or sold to another approved vendor.',

  '"For The Fans Fest", at its sole discretion, shall assign space at the show and will try to accommodate special requests. Exhibitors will only be allowed to use the space they are assigned. No space will be assigned without payment. Exhibitors will limit their display to the rented space as outlined in the agreement to be the exact size paid for and agree to not alter the convention floor plan in any way. No Exhibitors will be or are allowed to have any item(s) in the aisle space.',
  '"For The Fans Fest" reserves the right to rearrange the floor plan, alter entrances and exits and undertake structural changes as needed.',
  'The space Exhibitors purchase is for YOUR USE ONLY. NO SUBLETTING and/or RESELLING of space is allowed without permission. Sharing of space is also only allowed with permission in advance by UNDENIABLE VENTURES.',
  'Exhibitors will get up to 3 (three) Exhibitor wristbands which allow access to all activities. Lost wristbands will cost $50 (fifty dollars) each to replace.',
  'Electrical service is available for vendors inside the building vendor areas, cost is $150 (one hundred and fifty dollars) per electrical outlet and can be dropped at any booth indoors. Be aware electrical hookups will not be available day of show, so if you need electricity you need to reserve that when you book your exhibit space. Sometimes we can split the electrical fee between vendors positioned next to each other.',
  'We are only offering Exhibitors reserved space; tables must be requested ahead of time. Vendors will have access to free-for-use comfy chairs provided by the hotel and a table for no additional cost. Exhibitors can bring their own booth needs, although additional table rental is available through "For The Fans Fest" from the hotel for $100 (one hundred dollars) per table for the weekend; electricity and other booth needs can be ordered upon signing up for your space, or no later than fourteen (14) days in advance.',
  'Exhibitors must comply with all state and local laws.',
  'Exhibitors selling any consumable products must provide management with a current ServSafe Certificate along with having any needed State of NJ Board of Health approval. All Food and consumables services must comply with any State of NJ and Town Atlantic City regulations and be approved by hotel.',
  'Exhibitors will not and are not permitted to affix anything to the convention room walls. Any damage to the facility NOT reported to the "For The Fans Fest" upon arrival prior to set up, will completely be the responsibility of Exhibitor occupying the space; and said Exhibitor will be held personally responsible for said damage by hotel.',
  'Exhibitors will not bring any gambling devices (i.e. grab bags, dice games, card dispensing machines etc.) to be used on or near the premises without specific written consent. "For The Fans Fest" has the right to remove any offensive material displayed.',
  'Sale of firearms and/or any weapons of any kind are strictly prohibited from the property. All New Jersey weapons laws will be strictly enforced on the property.',
  'Exhibitors assume entire responsibility for themselves, their employees, their merchandise, their vehicle and their personal belongings and hereby agree to protect, indemnify, defend, save and hold harmless the "For The Fans Fest" UNDENIABLE VENTURES, including its owners, operators and staff, along with the Harrah’s Resort Atlantic City, its owners, operators and staff, along with all staff, sponsors and principles against all claims, losses and damages to person or property, governmental charges and or fines and attorney fees arising out of, or caused by, Exhibitor’s installation, removal, occupancy or use of the exhibition premises or any part thereof, from loss or damage of merchandise or injury sustained during attendance at its event. "For The Fans Fest" takes no responsibility for items lost or stolen: it is up to vendors to be diligent and/or carry insurance for their goods.',
  'Exhibitor understands that "For The Fans Fest" does not maintain insurance covering any Exhibitor, their employees, family, or helpers’ property, and it is the sole responsibility of Exhibitors to obtain any such insurance should Exhibitors want or need such insurance. "For The Fans Fest" maintains adequate insurance for coverage of liability due to accidents to attendees. We recommend any Exhibitor consider obtaining liability insurance for this event, and to include "For The Fans Fest" UNDENIABLE VENTURES, Harrah’s Resort Atlantic City and all of our owners, operators and staff.',
  'There will be security on premises, however "For The Fans Fest" is not responsible for exhibitor’s property. Be vigilant, not paranoid, and help each other if needed.',
  '"For The Fans Fest" RESERVES THE RIGHT TO DENY EXHIBITOR ACCESS TO EVENT IF THE COMPANY FEELS THAT PARTICIPATION BY A GROUP OR INDIVIDUAL WILL HARM THE EVENT OR OUR COMPANY IN ANY MANNER AND EVENT MANAGEMENT WILL BE THE FINAL ARBITER IN THESE DECISIONS.',
  'By submitting this application I AGREE TO ALL OF THE TERMS AND CONDITIONS outlined in the agreement in order to exhibit at the For The Fans Fest. I agree that all employees will also comply with all terms and conditions of this agreement. Any breach of this agreement will lead to immediate removal from premises with no option for refund. I agree to make payment promptly upon acceptance, and said acceptance may be revoked if not paid in a timely manner.',
];
